---
# Purpose: assert that the instance really ended up in the expected state.
# Molecule calls this playbook with `molecule verify`.
- name: Verify dependencies
  hosts: all
  gather_facts: true # Quicker, if you do not need facts
  vars:
    server_deploy_dir: /opt/hisohiso
    server_repo_url: "https://github.com/draganescu/hisohiso"
    server_repo_branch: "main"
  tasks:
    - name: Gather installed packages
      ansible.builtin.package_facts:
        manager: auto
    - name: Ensure git is installed on the host
      ansible.builtin.assert:
        that: '"git" in ansible_facts.packages'
    - name: Gather stats on deploy directory
      ansible.builtin.stat:
        path: "{{ server_deploy_dir }}"
      register: deploy_dir_stat

    - name: Ensure deploy directory exists
      ansible.builtin.assert:
        that:
          - deploy_dir_stat.stat.exists
          - deploy_dir_stat.stat.isdir

    - name: Gather stats on git directory
      ansible.builtin.stat:
        path: "{{ server_deploy_dir }}/.git"
      register: git_dir_stat

    - name: Ensure git exists
      ansible.builtin.assert:
        that:
          - git_dir_stat.stat.exists
          - git_dir_stat.stat.isdir

    - name: Gather stats on .env
      ansible.builtin.stat:
        path: "{{ server_deploy_dir }}/.env"
      register: env_stat

    - name: Ensure env exists
      ansible.builtin.assert:
        that:
          - env_stat.stat.exists
          - env_stat.stat.isreg
          - env_stat.stat.mode == "0600"

    - name: Read .env content
      ansible.builtin.slurp:
        src: "{{ server_deploy_dir }}/.env"
      register: env_content

    - name: Ensure .env contains required keys
      ansible.builtin.assert:
        that:
          - "'SERVER_NAME=' in env_content.content | b64decode"
          - "'MERCURE_PUBLISHER_JWT_KEY=' in env_content.content | b64decode"
          - "'MERCURE_SUBSCRIBER_JWT_KEY=' in env_content.content | b64decode"
          - "'MERCURE_HUB_URL=' in env_content.content | b64decode"

    - name: Gather stats on compose.yml
      ansible.builtin.stat:
        path: "{{ server_deploy_dir }}/compose.yaml"
      register: compose_yml_stat

    - name: Ensure required compose.yml exist in repository
      ansible.builtin.assert:
        that:
          - compose_yml_stat.stat.exists
          - compose_yml_stat.stat.isreg

    - name: Gather stats on compose.prod.yml
      ansible.builtin.stat:
        path: "{{ server_deploy_dir }}/compose.prod.yaml"
      register: compose_prod_yml_stat

    - name: Ensure required compose.prod.yml exist in repository
      ansible.builtin.assert:
        that:
          - compose_prod_yml_stat.stat.exists
          - compose_prod_yml_stat.stat.isreg