---
# Purpose: assert that the instance really ended up in the expected state.
# Molecule calls this playbook with `molecule verify`.
- name: Verify dependencies
  hosts: all
  gather_facts: true # Quicker, if you do not need facts
  tasks:
    - name: Gather installed packages
      ansible.builtin.package_facts:
        manager: auto
    - name: Ensure git is installed on the host
      ansible.builtin.assert:
        that: '"git" in ansible_facts.packages'
